### ISSUE TITLE
add ability to run all models at once

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#17]

**Comment by andrewbutterfield** [comment]
First step, is to run a model when not in its directory 

- testbuilder.yml defines model locations
- search down for model directories for <modelname>.pml

**Comment by andrewbutterfield** [comment]
When  #17 is done, then the `zero` command should get subsumed into a facility to deploy a given subset of all the models.

**Comment by andrewbutterfield** [comment]
- [ ] invoke as `testbuilder models`.
         current `all` becomes `allsteps` ?  
- [ ] how to identify models (e.g. path to model)
- [ ] command-line options - all vs. one model vs. specified sub-set
- [ ] check is a model actually a model? (use refine-config as a basis for checking

**Comment by GH-James** [comment]
>   current `all` becomes `allsteps` ?
> * [ ]  command-line options - all vs. one model vs. specified sub-set

I think the following could work for invoking allsteps for all, one, or a sub-set of models.

To run all models:
`tbuild allsteps allmodels`

To run one or more models simply give a list of models you would like to run.

Only chains:
`tbuild allsteps chains-api-model`

Chains and barrier manager:
`tbuild allsteps chains-api-model barrier-mgr-model`

**Comment by andrewbutterfield** [comment]
Looks good to me! 

Where do have to be to give this command?  In `models`? Anywhere below that? Anywhere above (e.g.`promela`)?

**Comment by GH-James** [comment]
I'm thinking this could run from anywhere, currently one model can be run from anywhere.

I will need to make some more changes to have it working as above.

**Comment by GH-James** [comment]
Yes, there is a new configuration item in testbuilder-template.yml
`modelsfile: <formal_directory>/promela/models/models.yml`

The ongoing merge request may also need to be completed, then added to this branch if you encounter the ubuntu issue again.

**Comment by andrewbutterfield** [comment]
MR now done

**Comment by GH-James** [comment]
Those changes are now in this RunAllModels branch

**Comment by andrewbutterfield** [comment]
This is good to go - do a PR

**Comment by andrewbutterfield** [comment]
PR accepted
