### ISSUE TITLE
automate tc-<model>.c generation

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#18]
We want to automatically generate the tc- files which currently have to be hand edited whenever a revised PML model changes number of tests.

e.g. `formal/promela/models/events/tc-event-mgr-model.c`

**Comment by GH-James** [comment]
I noticed that for event-mgr-model, 11 test and trail files are generated (0-10)
However, the test case file only 9 seem to be run (0-8)

I manually added 9 and 10 and encountered failures for case 10

```
E:RtemsModelSystemEventsMgr10:N:25:F:2:D:0.044310^M

...

E:RtemsModelEventsMgr10:N:25:F:2:D:0.044396^M
```
Resulting in a Non-zero exit code:
```
Z:Model1:C:22:N:486:F:4:D:0.861040^M
Y:ReportHash:SHA256:ZtMAiHymjLeLiaw4RkbhdzAzst5Zfus9vQnRlxlJVoA=^M
^M
*** EXIT STATUS NOT ZERO ***^M
```

The entire log is attached if there is anything else of relevance
[model-1-test.log](https://github.com/andrewbutterfield/RTEMS-SMP-Formal/files/10777890/model-1-test.log)
