### ISSUE TITLE
Strange failure when running on Ubuntu

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#21]
I installed python3.10 from source on a Ubuntu machine and then tried to do `gentest` (after `clean` and `spin`).

It starts OK
```
(env) events$ tb gentests event-mgr-model
Generating test files for event-mgr-model

	Spin2Test (Coconut/Python)


Test Number 0

!event-mgr-model-0.spn --(event-mgr-model-rfn.yml`)-> [event-mgr-model-pre.h;_;event-mgr-model-post.h;event-mgr-model-run.h] >> tr-event-mgr-model-0.c

!{} --({}`)-> [{};_;{};{}] >> {}

@@@ 0 NAME Event_Manager_TestGen
@@@ 0 DEF NO_OF_EVENTS 4
```
Shortly afterwardswe see (line 423):
```
pending_DCL: rtems_event_set {0}[TASK_MAX];
recout: T_eq_int( recout[{0}], {1} );
recout_DCL: rtems_event_set {0}[TASK_MAX];
recrc: T_rsc( recrc, {0} );
recrc_DCL: rtems_status_code
semaphore_DCL: rtems_id {0}[SEMA_MAX];
sendrc: T_rsc( sendrc, {0} );
sendrc_DCL: rtems_status_code

Set LANGUAGE to C (comments)

Unknown LANGUAGE C, set to C

Set LANGUAGE to C (comments)

Unknown LANGUAGE C, set to C
```
This repeats until line 4129 !!!

We end with:
```
Set LANGUAGE to C (comments)

Unknown LANGUAGE C, set to C

Traceback (most recent call last):
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/spin2test.py", line 1916, in <module>
    src.spin2test.main(cl_args.tstno, '', cl_args.root, cl_args.pre_amble, cl_args.post_amble, cl_args.run, cl_args.refine, cl_args.testfile)
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/spin2test.py", line 79, in main
    cmd = refine.command(ref_dict)
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/refine_command.py", line 54, in __init__
    self.setComments("C")
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/refine_command.py", line 76, in setComments
    self.setComments("C")
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/refine_command.py", line 76, in setComments
    self.setComments("C")
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/refine_command.py", line 76, in setComments
    self.setComments("C")
  [Previous line repeated 982 more times]
  File "/home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/src/refine_command.py", line 62, in setComments
    logger.debug(f"Set LANGUAGE to {language} (comments)\n")
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 679, in format
    if self.usesTime():
  File "/usr/local/lib/python3.10/logging/__init__.py", line 647, in usesTime
    return self._style.usesTime()
  File "/usr/local/lib/python3.10/logging/__init__.py", line 424, in usesTime
    return self._fmt.find(self.asctime_search) >= 0
RecursionError: maximum recursion depth exceeded while calling a Python object
error executing: python /home/butrfeld/REPOS/RTEMS-SMP-Formal/formal/promela/src/spin2test.py event-mgr-model event-mgr-model-pre.h event-mgr-model-post.h event-mgr-model-run.h event-mgr-model-rfn.yml tr-event-mgr-model-0.c 0
(env) events$ 
```
What does `usesTime` do?

Here is the whole log file:
[recfail.log](https://github.com/andrewbutterfield/RTEMS-SMP-Formal/files/10834630/recfail.log)

**Comment by GH-James** [comment]
usesTime looks like a red herring to me.
It looks as though it can't find the file "formal/promela/src/src/languages/c.yml"

As a result, it is recursing indefinitely as I have set c as the fall-back language.
I should add an error should it fail to set a fall-back language in case the language files get deleted by a user.

As for troubleshooting, my first guess would be that the file isn't available on your active branch.
Failing that, there could be an issue with case sensitivity that I haven't come across.

**Comment by andrewbutterfield** [comment]
Hi James,
Yes – make it an error.

It occurred because I tried to run it on an Ubuntu machine not used for a while.
I used the most recent version of main, and copied refine-config-template.yml to refine-config.yml,
but didn’t modify it.

It might be worth updating the README
– it doesn’t mention refine-config or any of the language stuff

? Why is the language setup recursive?

Regards, Andrew

--------------------------------------------------------------------
Andrew Butterfield     Tel: +353-1-896-2517     Fax: +353-1-677-2204
***@***.***, Head of Software Foundations & Verification Research Group
School of Computer Science and Statistics,
Room G.39, O'Reilly Institute, Trinity College, University of Dublin
                         http://www.scss.tcd.ie/Andrew.Butterfield/
--------------------------------------------------------------------


From: James Gooding Hunt ***@***.***>
Reply to: andrewbutterfield/RTEMS-SMP-Formal ***@***.***>
Date: Sunday 26 February 2023 at 21:18
To: andrewbutterfield/RTEMS-SMP-Formal ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Subject: Re: [andrewbutterfield/RTEMS-SMP-Formal] Strange failure when running on Ubuntu (Issue #21)


usesTime looks like a red herring to me.
It looks as though it can't find the file "formal/promela/src/src/languages/c.yml"

As a result, it is recursing indefinitely as I have set c as the fall-back language.
I should add an error should it fail to set a fall-back language in case the language files get deleted by a user.

As for troubleshooting, my first guess would be that the file isn't available on your active branch.
Failing that, there could be an issue with case sensitivity that I haven't come across.

**Comment by GH-James** [comment]
This should give now a clearer error message when the fall-back language file (c) is not found.

I've tested on native ubuntu installs and found that the paths are case sensitive with pathlib.
Strangely, I haven't come across this issue when using ubuntu on wsl.
I will work on a fix now.

**Comment by GH-James** [comment]
The error should be resolved if you attempt to run it.

I updated the readme to mention language agnostic functionality as well as local/global refine-config.yml and testbuild.yml files.
