### ISSUE TITLE
configure SPIN command line

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#4]
add config item for SPIN command line

```
os.system(f"spin -DTEST_GEN -run -E -c0 -e {model}.pml")
```

Use above as default

**Comment by GH-James** [comment]
```
testbuilder-template.yml
spintrailargs: -DTEST_GEN -run -E -c0 -e # trail generation "spin <spintrailargs> <model>.pml"
```

Thoughts on config item name?

**Comment by andrewbutterfield** [comment]
I'd not focus on the "trail" aspect, as we then use that to get the "spn" stuff. A better term is "scenario". What this does is describe how to generate all possible scenarios, so perhaps something like `spinallscenarios` ?

**Comment by andrewbutterfield** [comment]
Actually, that's just in the commit message

**Comment by andrewbutterfield** [comment]
Works fine
