### ISSUE TITLE
split generate

### ISSUE THREAD

**Issue by andrewbutterfield** [andrewbutterfield/RTEMS-SMP-Formal#6]
split `generate` into two,
one does the SPIN stuff, the other does the testgen stuff.

What do we call these commands?

First two generate scenarios from the model

Last one refines this into test code

**Comment by GH-James** [comment]
Currently using 3 variations for generate
```
'generate <model>' will run SPIN to find all scenarios, and produce C tests
'spin <model>' will run SPIN to find all scenarios
'gentests <model>' will produce C tests
```

Do you think it makes sense to keep generate, or remove it completely?

**Comment by andrewbutterfield** [comment]
Let's remove `generate`  in this case. Keeps things simpler given that we are going to have a "do all" command

**Comment by andrewbutterfield** [comment]
Works fine.
